import React from 'react';
import { StackupConfig, SimulationResult } from '../types';
import { StackupPlot } from './StackupPlot';
import { SummaryPanel } from './SummaryPanel';
import { ResultCharts } from './ResultCharts';
import { DimensionTable } from './DimensionTable';
import { Layers, Calendar } from 'lucide-react';

interface Props {
  config: StackupConfig;
  results: SimulationResult | null;
}

export const FullReport: React.FC<Props> = ({ config, results }) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  return (
    <div className="bg-white p-8 max-w-[1000px] mx-auto space-y-8">
      {/* Report Header */}
      <div className="flex justify-between items-end border-b pb-6 border-slate-200">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="bg-blue-600 text-white p-2 rounded-lg">
              <Layers size={24} />
            </div>
            <h1 className="text-2xl font-bold text-slate-900">Tolerance Analysis Report</h1>
          </div>
          <h2 className="text-lg text-slate-600 font-medium">{config.name}</h2>
          {config.description && (
            <p className="text-sm text-slate-500 mt-1">{config.description}</p>
          )}
        </div>
        <div className="text-right text-sm text-slate-500">
          <div className="flex items-center justify-end gap-2 mb-1">
            <Calendar size={14} />
            <span>{currentDate}</span>
          </div>
          <p>Generated by TolStack Pro</p>
        </div>
      </div>

      {/* Stackup Visualization */}
      <div className="space-y-4">
        <h3 className="text-lg font-bold text-slate-800 border-l-4 border-blue-500 pl-3">Stackup Visualization</h3>
        <div className="bg-slate-50/50 p-4 rounded-xl border border-slate-200">
          <StackupPlot dimensions={config.dimensions} results={results} />
        </div>
      </div>

      {/* Dimension Details */}
      <div className="space-y-4">
        <h3 className="text-lg font-bold text-slate-800 border-l-4 border-blue-500 pl-3">Dimension Loop Details</h3>
        <DimensionTable dimensions={config.dimensions} />
      </div>

      {/* Analysis Results */}
      {results && (
        <div className="space-y-6">
          <h3 className="text-lg font-bold text-slate-800 border-l-4 border-blue-500 pl-3">Analysis Results</h3>
          
          {/* Summary Stats */}
          <SummaryPanel results={results} config={config} />
          
          {/* Charts */}
          <div className="grid grid-cols-1 gap-6">
            <ResultCharts results={results} config={config} />
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="pt-8 mt-8 border-t border-slate-100 text-center text-xs text-slate-400">
        <p>This report was automatically generated. Verify all inputs and assumptions before use in critical applications.</p>
      </div>
    </div>
  );
};
